version: '3.8'

networks:
  internal_net:
    driver: bridge
    internal: true

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      
    container_name: backend
    #ports:
    #  - "5000:5000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes: 
  mydata:
